language: java

jdk:
  - openjdk11

# Overridden because parent project uses maven.test.skip instead of skipTests
install:
  - mvn -s src/test/resources/settings.xml -q package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V

script:
  - >
    mvn -s src/test/resources/settings.xml help:active-profiles verify \
      -Dorg.slf4j.simpleLogger.log.net.sourceforge.pmd=error \

after_success:
  - chmod 755 src/main/tools/travis/*
  - src/main/tools/travis/get_build_key $encrypted_fdf3b6311250_key $encrypted_fdf3b6311250_iv
  - src/main/tools/travis/deploy

cache:
  directories:
    - $HOME/.m2

# The only branch we build on is "v3"; all other builds are done on PRs to "v3"
branches:
  only:
  - v3

notifications:
  email:
    recipients:
    - ksclarke@ksclarke.io
    on_failure: change
    on_success: change

sudo: false
